[package]
name = "c_to_rust"
version = "0.1.0"
authors = ["Baranyi Károly"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["staticlib"]